// Creates a print window that users can "Save as PDF" from the browser.
// No external dependencies (keeps "replace src" workflow simple).

export function openPrintWindow({ title, html, landscape = true }) {
  const w = window.open('', '_blank', 'noopener,noreferrer');
  if (!w) {
    alert('Popup blocked. Please allow popups for PDF export.');
    return;
  }

  const safeTitle = String(title || 'Export').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  w.document.open();
  w.document.write(`<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>${safeTitle}</title>
      <style>
        @page { size: ${landscape ? 'A4 landscape' : 'A4 portrait'}; margin: 12mm; }
        * { box-sizing: border-box; }
        body { font-family: Arial, Helvetica, sans-serif; color: #111; }
        h1 { margin: 0 0 10px 0; font-size: 16px; }
        .meta { font-size: 11px; opacity: 0.85; margin-bottom: 10px; }
        .legend { display: flex; gap: 6px; align-items: center; flex-wrap: wrap; margin: 10px 0 14px; }
        .pill { display:inline-flex; align-items:center; justify-content:center; min-width: 26px; padding: 4px 8px; border-radius: 999px; font-weight: 700; font-size: 11px; border: 1px solid #9e9e9e; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        thead { display: table-header-group; }
        th, td { border: 1px solid #9e9e9e; padding: 6px; font-size: 10px; vertical-align: top; word-break: break-word; }
        th { background: #f5f5f5; font-weight: 700; }
        .page { page-break-after: always; }
        .page:last-child { page-break-after: auto; }
        .right { text-align: right; }
        .center { text-align: center; }
        .muted { opacity: 0.7; }
        .footer { position: fixed; bottom: 6mm; right: 12mm; font-size: 10px; opacity: 0.65; }
      </style>
    </head>
    <body>
      ${html}
      <div class="footer">Generated by Training & Competency</div>
      <script>
        // Wait a tick so layout paints before print dialog opens.
        setTimeout(() => { window.print(); }, 100);
      </script>
    </body>
  </html>`);
  w.document.close();
}
