// Creates a print document and triggers the browser print dialog (users can "Save as PDF").
// Uses a hidden iframe (avoids popup blockers).

export function openPrintWindow({ title, html, landscape = true }) {
  // Create a hidden iframe so we don't rely on window.open (which is often blocked).
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  iframe.style.opacity = '0';
  iframe.setAttribute('aria-hidden', 'true');

  // Some browsers require allow-modals for print dialogs inside iframes.
  iframe.setAttribute('sandbox', 'allow-same-origin allow-modals');

  document.body.appendChild(iframe);

  const safeTitle = String(title || 'Export')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) {
    // Fallback (very rare): try window.open
    const w = window.open('', '_blank', 'noopener,noreferrer');
    if (!w) {
      alert('Popup blocked. Please allow popups for PDF export.');
      iframe.remove();
      return;
    }
    w.document.open();
    w.document.write(buildHtml({ safeTitle, html, landscape }));
    w.document.close();
    return;
  }

  doc.open();
  doc.write(buildHtml({ safeTitle, html, landscape }));
  doc.close();

  // Give the browser a moment to layout before printing.
  setTimeout(() => {
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } finally {
      // Cleanup after a short delay (so print dialog has time to open).
      setTimeout(() => {
        iframe.remove();
      }, 1000);
    }
  }, 150);
}

function buildHtml({ safeTitle, html, landscape }) {
  const pageSize = landscape ? 'A4 landscape' : 'A4 portrait';

  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>${safeTitle}</title>
      <style>
        @page { size: ${pageSize}; margin: 10mm 12mm; }
        body { font-family: Arial, Helvetica, sans-serif; color: #111; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 6px 8px; font-size: 12px; }
        th { background: #f5f5f5; text-align: left; }
        .header { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 10px; }
        .title { font-size: 18px; font-weight: 700; }
        .meta { font-size: 12px; opacity: 0.7; }
        .footer { position: fixed; bottom: 6mm; right: 12mm; font-size: 10px; opacity: 0.65; }
      </style>
    </head>
    <body>
      ${html}
      <div class="footer">Generated by Training & Competency</div>
    </body>
  </html>`;
}
